from . import fleet_vehicle_odometer
from . import fleet_vehicle
from . import gps_alerts
from . import gps_commands
from . import gps_devices
from . import gps_geofences
from . import gps_positions
from . import gps_protocol
from . import models
from . import res_config_settings
